import jsPDF from "jspdf";

export interface SprintDocumentation {
  overview: string;
  objectives: string[];
  success_criteria: string[];
  riskSummary: string;
}

export interface SprintInfo {
  name: string;
  goal?: string;
  startDate?: string;
  endDate?: string;
  duration?: number;
}
export function downloadSprintDocumentationAsCompactPDF(
  sprintInfo: SprintInfo,
  documentation: SprintDocumentation
) {
  const doc = new jsPDF();

  // Set font
  doc.setFont("helvetica");

  // Page dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  let yPosition = margin;

  // Header with SprintiQ branding
  doc.setFillColor(10, 53, 52); // Emerald color
  doc.rect(0, 0, pageWidth, 28, "F");

  // Add logo
  try {
    const logo = new Image();
    logo.src = "/images/sprintiq-logo.png";
    doc.addImage(logo, "PNG", margin, 6, 40, 12);
  } catch (error) {
    // Fallback to text
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("SprintiQ", margin, 20);
  }

  // Document title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  const titleText = "Sprint Documentation";
  const titleWidth = doc.getTextWidth(titleText);
  doc.text(titleText, pageWidth - margin - titleWidth, 16);

  yPosition = 45;
  doc.setTextColor(0, 0, 0);

  // Sprint name
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(16, 185, 129);
  doc.text(sprintInfo.name, margin, yPosition);
  yPosition += 8;

  // Sprint info
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(75, 85, 99);

  if (sprintInfo.goal) {
    const contentLines = doc.splitTextToSize(
      `Goal: ${sprintInfo.goal}`,
      contentWidth
    );
    doc.text(contentLines, margin, yPosition);
    yPosition += contentLines.length * 4 + 3;
  }
  if (sprintInfo.startDate && sprintInfo.endDate) {
    const contentLines = doc.splitTextToSize(
      `Duration: ${sprintInfo.startDate} - ${sprintInfo.endDate}`,
      contentWidth
    );
    doc.text(contentLines, margin, yPosition);
    yPosition += contentLines.length * 4 + 10;
  } else if (sprintInfo.duration) {
    const contentLines = doc.splitTextToSize(
      `Duration: ${sprintInfo.duration} weeks`,
      contentWidth
    );
    doc.text(contentLines, margin, yPosition);
    yPosition += contentLines.length * 4 + 10;
  }

  // Content sections
  const sections = [
    { title: "Overview", content: documentation.overview },
    {
      title: "Objectives",
      content: "• " + documentation.objectives.join("\n• "),
    },
    {
      title: "Success Criteria",
      content: "• " + documentation.success_criteria.join("\n• "),
    },
    { title: "Risk Summary", content: documentation.riskSummary },
  ];

  sections.forEach((section, index) => {
    if (yPosition > pageHeight - 80) {
      doc.addPage();
      yPosition = margin;

      // Add SprintiQ logo to new page
      doc.setFillColor(16, 185, 129);
      doc.rect(0, 0, pageWidth, 25, "F");
      try {
        const logo = new Image();
        logo.src = "/images/sprintiq-logo.png";
        doc.addImage(logo, "PNG", margin, 2, 35, 20);
      } catch (error) {
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("SprintiQ", margin, 17);
      }
      yPosition = 35;
    }

    // Section title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text(section.title, margin, yPosition);
    yPosition += 8;

    // Section content
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);

    const contentLines = doc.splitTextToSize(section.content, contentWidth);
    doc.text(contentLines, margin, yPosition);
    yPosition += contentLines.length * 4 + 10;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(75, 85, 99);
  doc.text("Generated by SprintiQ", margin, pageHeight - 15);
  doc.text(
    `Generated on: ${new Date().toLocaleDateString()}`,
    margin,
    pageHeight - 10
  );

  // Save the PDF
  const filename = `${sprintInfo.name
    .replace(/[^a-z0-9]/gi, "_")
    .toLowerCase()}_sprint_documentation_compact.pdf`;
  doc.save(filename);
}
