export interface RoleTemplate {
  id: string;
  name: string;
  description: string;
  experience: string;
  category: string;
  core_competencies: {
    [key: string]: string[];
  };
  template_data: {
    icon: string;
    color: string;
    tags: string[];
    difficulty: "beginner" | "intermediate" | "advanced";
  };
}

export const roleTemplates: RoleTemplate[] = [
  // Engineering Roles
  {
    id: "ai-ml-engineer",
    name: "AI/ML Engineer",
    description:
      "Designs, builds, and deploys machine learning models and AI systems to solve complex business problems. Transforms raw data into intelligent solutions through statistical analysis, algorithm development, and scalable model deployment.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      machine_learning: [
        "supervised_learning",
        "unsupervised_learning",
        "deep_learning",
        "neural_networks",
        "computer_vision",
        "nlp",
        "reinforcement_learning",
        "model_optimization",
        "feature_engineering",
      ],
      frameworks_tools: [
        "tensorflow",
        "pytorch",
        "scikit_learn",
        "keras",
        "huggingface",
        "opencv",
        "pandas",
        "numpy",
        "matplotlib",
        "jupyter",
      ],
      programming: [
        "python",
        "r",
        "sql",
        "bash",
        "git",
        "docker",
        "kubernetes",
        "aws",
        "gcp",
        "azure",
      ],
      deployment: [
        "mlops",
        "model_serving",
        "api_development",
        "cloud_platforms",
        "monitoring",
        "a_b_testing",
        "ci_cd",
        "containerization",
      ],
    },
    template_data: {
      icon: "brain",
      color: "purple",
      tags: ["ai", "ml", "data", "engineering"],
      difficulty: "advanced",
    },
  },
  {
    id: "cloud-engineer",
    name: "Cloud Engineer",
    description:
      "Designs, implements, and manages scalable cloud infrastructure and services. Ensures high availability, security, and cost optimization while enabling seamless deployment and operation of applications in cloud environments.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      cloud_platforms: [
        "aws",
        "azure",
        "gcp",
        "alibaba_cloud",
        "oracle_cloud",
        "multi_cloud",
        "hybrid_cloud",
      ],
      infrastructure_as_code: [
        "terraform",
        "cloudformation",
        "arm_templates",
        "pulumi",
        "ansible",
        "chef",
        "puppet",
      ],
      containerization: [
        "docker",
        "kubernetes",
        "openshift",
        "ecs",
        "aks",
        "gke",
        "helm",
        "istio",
      ],
      devops_automation: [
        "ci_cd",
        "jenkins",
        "gitlab_ci",
        "github_actions",
        "azure_devops",
        "monitoring",
        "logging",
        "alerting",
      ],
      security_compliance: [
        "iam",
        "vpc",
        "security_groups",
        "ssl_tls",
        "encryption",
        "compliance",
        "vulnerability_scanning",
      ],
      programming_scripting: [
        "python",
        "bash",
        "powershell",
        "yaml",
        "json",
        "go",
        "nodejs",
      ],
    },
    template_data: {
      icon: "cloud",
      color: "blue",
      tags: ["cloud", "infrastructure", "devops"],
      difficulty: "advanced",
    },
  },
  {
    id: "data-engineer",
    name: "Data Engineer",
    description:
      "Builds and maintains robust data pipelines and infrastructure that enable efficient collection, processing, and storage of large-scale data. Ensures data quality, accessibility, and reliability for analytics and machine learning workflows.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      data_pipelines: [
        "etl",
        "elt",
        "data_streaming",
        "batch_processing",
        "real_time_processing",
        "data_orchestration",
        "workflow_automation",
      ],
      big_data_tools: [
        "apache_spark",
        "hadoop",
        "kafka",
        "airflow",
        "databricks",
        "snowflake",
        "redshift",
        "bigquery",
      ],
      databases: [
        "postgresql",
        "mysql",
        "mongodb",
        "cassandra",
        "elasticsearch",
        "redis",
        "dynamodb",
        "cosmos_db",
      ],
      programming: [
        "python",
        "sql",
        "scala",
        "java",
        "bash",
        "r",
        "pyspark",
        "pandas",
        "numpy",
      ],
      cloud_platforms: [
        "aws",
        "azure",
        "gcp",
        "s3",
        "azure_data_factory",
        "cloud_dataflow",
        "lambda",
        "azure_functions",
      ],
      data_modeling: [
        "dimensional_modeling",
        "data_warehousing",
        "data_lakes",
        "schema_design",
        "normalization",
        "star_schema",
        "snowflake_schema",
      ],
    },
    template_data: {
      icon: "database",
      color: "green",
      tags: ["data", "engineering", "pipelines"],
      difficulty: "advanced",
    },
  },
  {
    id: "security-engineer",
    name: "Security Engineer",
    description:
      "Designs, implements, and maintains security systems and protocols to protect organizational infrastructure, applications, and data. Identifies vulnerabilities, responds to security incidents, and ensures compliance with security standards and regulations.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      security_fundamentals: [
        "threat_modeling",
        "risk_assessment",
        "vulnerability_management",
        "penetration_testing",
        "security_architecture",
        "cryptography",
        "secure_coding",
        "security_auditing",
      ],
      cloud_security: [
        "aws_security",
        "azure_security",
        "gcp_security",
        "iam",
        "vpc_security",
        "cloud_compliance",
        "container_security",
        "serverless_security",
      ],
      network_security: [
        "firewalls",
        "intrusion_detection",
        "intrusion_prevention",
        "vpn",
        "network_segmentation",
        "dns_security",
        "ddos_protection",
        "network_monitoring",
      ],
      application_security: [
        "secure_sdlc",
        "code_review",
        "static_analysis",
        "dynamic_analysis",
        "api_security",
        "web_security",
        "mobile_security",
        "dependency_scanning",
      ],
      security_tools: [
        "splunk",
        "elk_stack",
        "nessus",
        "burp_suite",
        "metasploit",
        "wireshark",
        "nmap",
        "qualys",
        "crowdstrike",
        "okta",
      ],
      compliance_governance: [
        "iso_27001",
        "soc_2",
        "gdpr",
        "hipaa",
        "pci_dss",
        "nist",
        "cis_controls",
        "policy_development",
        "audit_preparation",
      ],
      incident_response: [
        "threat_hunting",
        "forensics",
        "incident_analysis",
        "malware_analysis",
        "security_monitoring",
        "siem",
        "soar",
        "playbook_development",
      ],
      programming_scripting: [
        "python",
        "bash",
        "powershell",
        "javascript",
        "sql",
        "regex",
        "automation",
        "api_integration",
      ],
    },
    template_data: {
      icon: "shield",
      color: "red",
      tags: ["security", "engineering", "compliance"],
      difficulty: "advanced",
    },
  },
  {
    id: "platform-engineer",
    name: "Platform Engineer",
    description:
      "Builds and maintains internal developer platforms and infrastructure that enable teams to deploy, operate, and scale applications efficiently. Creates self-service tools and automated workflows that improve developer productivity and system reliability.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      infrastructure_as_code: [
        "terraform",
        "pulumi",
        "cloudformation",
        "arm_templates",
        "ansible",
        "chef",
        "puppet",
        "helm_charts",
      ],
      container_orchestration: [
        "kubernetes",
        "docker",
        "openshift",
        "ecs",
        "aks",
        "gke",
        "helm",
        "kustomize",
        "istio",
        "linkerd",
      ],
      cloud_platforms: [
        "aws",
        "azure",
        "gcp",
        "multi_cloud",
        "hybrid_cloud",
        "edge_computing",
        "serverless",
        "cloud_native",
      ],
      ci_cd_automation: [
        "jenkins",
        "gitlab_ci",
        "github_actions",
        "azure_devops",
        "tekton",
        "argo_cd",
        "flux",
        "pipeline_orchestration",
      ],
      monitoring_observability: [
        "prometheus",
        "grafana",
        "elk_stack",
        "splunk",
        "datadog",
        "new_relic",
        "jaeger",
        "zipkin",
        "opentelemetry",
      ],
      developer_experience: [
        "internal_platforms",
        "developer_portals",
        "self_service_tools",
        "documentation",
        "onboarding_automation",
        "cli_tools",
        "api_gateways",
      ],
      programming_scripting: [
        "python",
        "go",
        "bash",
        "powershell",
        "yaml",
        "json",
        "nodejs",
        "rust",
      ],
      databases_storage: [
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "s3",
        "blob_storage",
        "backup_strategies",
      ],
      networking_security: [
        "vpc",
        "load_balancers",
        "cdn",
        "dns",
        "ssl_tls",
        "iam",
        "rbac",
        "network_policies",
        "security_scanning",
      ],
      service_mesh: [
        "istio",
        "linkerd",
        "consul_connect",
        "envoy",
        "traffic_management",
        "service_discovery",
        "circuit_breakers",
      ],
    },
    template_data: {
      icon: "layers",
      color: "indigo",
      tags: ["platform", "engineering", "devops"],
      difficulty: "advanced",
    },
  },

  // Product Roles
  {
    id: "analytics-product-manager",
    name: "Analytics Product Manager",
    description:
      "Drives product strategy and development for analytics platforms and data products. Translates business requirements into technical specifications while collaborating with engineering, data science, and stakeholder teams to deliver impactful data solutions.",
    experience: "3+ years",
    category: "Product",
    core_competencies: {
      product_management: [
        "product_strategy",
        "roadmap_planning",
        "user_research",
        "requirements_gathering",
        "stakeholder_management",
        "agile_scrum",
        "product_analytics",
        "a_b_testing",
      ],
      analytics_tools: [
        "tableau",
        "power_bi",
        "looker",
        "qlik",
        "google_analytics",
        "adobe_analytics",
        "mixpanel",
        "amplitude",
        "segment",
      ],
      data_analysis: [
        "sql",
        "python",
        "r",
        "excel",
        "statistical_analysis",
        "data_visualization",
        "cohort_analysis",
        "funnel_analysis",
        "retention_metrics",
      ],
      technical_understanding: [
        "data_warehousing",
        "etl_processes",
        "apis",
        "data_modeling",
        "cloud_platforms",
        "database_concepts",
        "machine_learning_basics",
      ],
      business_skills: [
        "market_research",
        "competitive_analysis",
        "roi_analysis",
        "kpi_definition",
        "business_intelligence",
        "cross_functional_collaboration",
        "presentation_skills",
        "project_management",
      ],
      communication: [
        "technical_writing",
        "data_storytelling",
        "executive_reporting",
        "user_documentation",
        "training_delivery",
        "change_management",
      ],
    },
    template_data: {
      icon: "chart-line",
      color: "orange",
      tags: ["product", "analytics", "management"],
      difficulty: "intermediate",
    },
  },

  // Design Roles
  {
    id: "ux-researcher",
    name: "UX Researcher",
    description:
      "Conducts user research to understand user needs, behaviors, and motivations. Provides insights that inform product design decisions and improve user experience through data-driven research methodologies.",
    experience: "2+ years",
    category: "Design",
    core_competencies: {
      research_methods: [
        "user_interviews",
        "usability_testing",
        "surveys",
        "focus_groups",
        "card_sorting",
        "tree_testing",
        "a_b_testing",
        "analytics_analysis",
      ],
      analysis_tools: [
        "figma",
        "maze",
        "usertesting",
        "hotjar",
        "google_analytics",
        "mixpanel",
        "dovetail",
        "notion",
      ],
      communication: [
        "research_presentations",
        "persona_development",
        "journey_mapping",
        "stakeholder_management",
        "cross_functional_collaboration",
        "documentation",
      ],
      technical_skills: [
        "statistical_analysis",
        "data_visualization",
        "survey_design",
        "research_planning",
        "synthesis_techniques",
      ],
    },
    template_data: {
      icon: "search",
      color: "pink",
      tags: ["ux", "research", "design"],
      difficulty: "intermediate",
    },
  },

  // Business Roles
  {
    id: "business-analyst",
    name: "Business Analyst",
    description:
      "Analyzes business processes, requirements, and data to identify opportunities for improvement and optimization. Bridges the gap between business stakeholders and technical teams to ensure successful project delivery.",
    experience: "2+ years",
    category: "Business",
    core_competencies: {
      analysis_skills: [
        "requirements_gathering",
        "process_mapping",
        "gap_analysis",
        "root_cause_analysis",
        "swot_analysis",
        "cost_benefit_analysis",
        "risk_assessment",
      ],
      tools_technologies: [
        "excel",
        "sql",
        "power_bi",
        "tableau",
        "jira",
        "confluence",
        "visio",
        "lucidchart",
      ],
      business_domains: [
        "finance",
        "operations",
        "marketing",
        "sales",
        "hr",
        "supply_chain",
        "customer_service",
      ],
      communication: [
        "stakeholder_management",
        "presentation_skills",
        "documentation",
        "training",
        "change_management",
        "cross_functional_collaboration",
      ],
    },
    template_data: {
      icon: "trending-up",
      color: "emerald",
      tags: ["business", "analysis", "requirements"],
      difficulty: "intermediate",
    },
  },

  // Additional Engineering Roles
  {
    id: "frontend-developer",
    name: "Frontend Developer",
    description:
      "Develops user-facing features and interfaces using modern web technologies. Creates responsive, accessible, and performant web applications that provide excellent user experiences across different devices and browsers.",
    experience: "2+ years",
    category: "Engineering",
    core_competencies: {
      frontend_frameworks: [
        "react",
        "vue",
        "angular",
        "svelte",
        "nextjs",
        "nuxt",
        "gatsby",
        "remix",
      ],
      programming_languages: [
        "javascript",
        "typescript",
        "html",
        "css",
        "sass",
        "scss",
        "less",
        "stylus",
      ],
      styling_tools: [
        "tailwind_css",
        "styled_components",
        "emotion",
        "css_modules",
        "bootstrap",
        "material_ui",
        "chakra_ui",
        "ant_design",
      ],
      build_tools: [
        "webpack",
        "vite",
        "rollup",
        "parcel",
        "esbuild",
        "babel",
        "postcss",
        "autoprefixer",
      ],
      testing: [
        "jest",
        "vitest",
        "cypress",
        "playwright",
        "testing_library",
        "enzyme",
        "storybook",
        "chromatic",
      ],
      performance: [
        "lighthouse",
        "web_vitals",
        "bundle_analysis",
        "code_splitting",
        "lazy_loading",
        "caching",
        "cdn",
        "optimization",
      ],
    },
    template_data: {
      icon: "monitor",
      color: "blue",
      tags: ["frontend", "web", "ui"],
      difficulty: "intermediate",
    },
  },
  {
    id: "backend-developer",
    name: "Backend Developer",
    description:
      "Develops server-side logic, APIs, and database systems that power web and mobile applications. Ensures scalable, secure, and maintainable backend infrastructure with proper data management and API design.",
    experience: "2+ years",
    category: "Engineering",
    core_competencies: {
      programming_languages: [
        "python",
        "java",
        "csharp",
        "nodejs",
        "go",
        "rust",
        "php",
        "ruby",
      ],
      frameworks: [
        "django",
        "flask",
        "fastapi",
        "spring_boot",
        "express",
        "nest",
        "gin",
        "actix",
      ],
      databases: [
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "cassandra",
        "dynamodb",
        "sqlite",
      ],
      api_design: [
        "rest_apis",
        "graphql",
        "grpc",
        "openapi",
        "swagger",
        "api_versioning",
        "rate_limiting",
        "authentication",
      ],
      cloud_platforms: [
        "aws",
        "azure",
        "gcp",
        "heroku",
        "vercel",
        "netlify",
        "digital_ocean",
        "linode",
      ],
      devops_tools: [
        "docker",
        "kubernetes",
        "jenkins",
        "github_actions",
        "gitlab_ci",
        "terraform",
        "ansible",
        "monitoring",
      ],
    },
    template_data: {
      icon: "server",
      color: "green",
      tags: ["backend", "api", "server"],
      difficulty: "intermediate",
    },
  },
  {
    id: "fullstack-developer",
    name: "Full-Stack Developer",
    description:
      "Develops both frontend and backend components of web applications. Handles the complete development lifecycle from user interface design to server-side logic and database management.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      frontend_skills: [
        "react",
        "vue",
        "angular",
        "javascript",
        "typescript",
        "html",
        "css",
        "responsive_design",
      ],
      backend_skills: [
        "nodejs",
        "python",
        "java",
        "csharp",
        "php",
        "ruby",
        "api_development",
        "database_design",
      ],
      databases: [
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "sqlite",
        "database_migration",
        "orm",
        "query_optimization",
      ],
      deployment: [
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "heroku",
        "vercel",
        "ci_cd",
      ],
      testing: [
        "unit_testing",
        "integration_testing",
        "e2e_testing",
        "jest",
        "cypress",
        "testing_library",
        "tdd",
        "bdd",
      ],
      tools: [
        "git",
        "github",
        "gitlab",
        "webpack",
        "babel",
        "eslint",
        "prettier",
        "postman",
      ],
    },
    template_data: {
      icon: "layers",
      color: "purple",
      tags: ["fullstack", "web", "development"],
      difficulty: "advanced",
    },
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    description:
      "Manages infrastructure, deployment processes, and automation workflows. Ensures reliable, scalable, and secure application deployment with continuous integration and delivery practices.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      cloud_platforms: [
        "aws",
        "azure",
        "gcp",
        "digital_ocean",
        "linode",
        "multi_cloud",
        "hybrid_cloud",
        "cloud_migration",
      ],
      containerization: [
        "docker",
        "kubernetes",
        "openshift",
        "rancher",
        "helm",
        "kustomize",
        "container_registry",
        "orchestration",
      ],
      infrastructure_as_code: [
        "terraform",
        "cloudformation",
        "pulumi",
        "ansible",
        "chef",
        "puppet",
        "saltstack",
        "arm_templates",
      ],
      ci_cd: [
        "jenkins",
        "gitlab_ci",
        "github_actions",
        "azure_devops",
        "circleci",
        "travis_ci",
        "bamboo",
        "teamcity",
      ],
      monitoring: [
        "prometheus",
        "grafana",
        "datadog",
        "new_relic",
        "splunk",
        "elk_stack",
        "zabbix",
        "nagios",
      ],
      security: [
        "vulnerability_scanning",
        "security_auditing",
        "compliance",
        "secrets_management",
        "iam",
        "network_security",
        "container_security",
        "devsecops",
      ],
    },
    template_data: {
      icon: "settings",
      color: "orange",
      tags: ["devops", "infrastructure", "automation"],
      difficulty: "advanced",
    },
  },
  {
    id: "qa-engineer",
    name: "QA Engineer",
    description:
      "Tests software quality and ensures bug-free releases through comprehensive testing strategies. Designs and implements automated testing frameworks to maintain high code quality and user satisfaction.",
    experience: "2+ years",
    category: "Engineering",
    core_competencies: {
      testing_methodologies: [
        "manual_testing",
        "automated_testing",
        "unit_testing",
        "integration_testing",
        "system_testing",
        "acceptance_testing",
        "performance_testing",
        "security_testing",
      ],
      automation_tools: [
        "selenium",
        "cypress",
        "playwright",
        "puppeteer",
        "testcafe",
        "katalon",
        "appium",
        "rest_assured",
      ],
      programming: [
        "java",
        "python",
        "javascript",
        "csharp",
        "ruby",
        "php",
        "typescript",
        "bash",
      ],
      test_frameworks: [
        "junit",
        "testng",
        "pytest",
        "jest",
        "mocha",
        "jasmine",
        "nunit",
        "rspec",
      ],
      ci_cd_integration: [
        "jenkins",
        "gitlab_ci",
        "github_actions",
        "azure_devops",
        "bamboo",
        "teamcity",
        "circleci",
        "travis_ci",
      ],
      bug_tracking: [
        "jira",
        "bugzilla",
        "mantis",
        "redmine",
        "azure_devops",
        "github_issues",
        "linear",
        "asana",
      ],
    },
    template_data: {
      icon: "shield-check",
      color: "green",
      tags: ["qa", "testing", "quality"],
      difficulty: "intermediate",
    },
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    description:
      "Analyzes complex data to extract insights and build predictive models. Combines statistical analysis, machine learning, and domain expertise to solve business problems and drive data-driven decision making.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      programming: [
        "python",
        "r",
        "sql",
        "scala",
        "julia",
        "matlab",
        "sas",
        "spss",
      ],
      machine_learning: [
        "supervised_learning",
        "unsupervised_learning",
        "deep_learning",
        "reinforcement_learning",
        "feature_engineering",
        "model_selection",
        "hyperparameter_tuning",
        "cross_validation",
      ],
      frameworks: [
        "scikit_learn",
        "tensorflow",
        "pytorch",
        "keras",
        "pandas",
        "numpy",
        "scipy",
        "statsmodels",
      ],
      data_visualization: [
        "matplotlib",
        "seaborn",
        "plotly",
        "d3js",
        "tableau",
        "power_bi",
        "ggplot2",
        "bokeh",
      ],
      big_data: [
        "hadoop",
        "spark",
        "kafka",
        "hive",
        "pig",
        "hbase",
        "cassandra",
        "elasticsearch",
      ],
      statistics: [
        "descriptive_statistics",
        "inferential_statistics",
        "hypothesis_testing",
        "regression_analysis",
        "time_series",
        "bayesian_statistics",
        "ab_testing",
        "experimental_design",
      ],
    },
    template_data: {
      icon: "brain",
      color: "purple",
      tags: ["data", "ml", "analytics"],
      difficulty: "advanced",
    },
  },
  {
    id: "system-administrator",
    name: "System Administrator",
    description:
      "Manages IT systems and infrastructure to ensure optimal performance, security, and reliability. Maintains servers, networks, and software systems while providing technical support and implementing best practices.",
    experience: "3+ years",
    category: "Engineering",
    core_competencies: {
      operating_systems: [
        "linux",
        "windows_server",
        "unix",
        "centos",
        "ubuntu",
        "red_hat",
        "debian",
        "suse",
      ],
      networking: [
        "tcp_ip",
        "dns",
        "dhcp",
        "vpn",
        "firewalls",
        "routing",
        "switching",
        "load_balancing",
      ],
      virtualization: [
        "vmware",
        "hyper_v",
        "virtualbox",
        "kvm",
        "xen",
        "proxmox",
        "containers",
        "docker",
      ],
      monitoring: [
        "nagios",
        "zabbix",
        "prometheus",
        "grafana",
        "splunk",
        "elk_stack",
        "new_relic",
        "datadog",
      ],
      automation: [
        "ansible",
        "puppet",
        "chef",
        "saltstack",
        "powershell",
        "bash",
        "python",
        "ruby",
      ],
      security: [
        "access_control",
        "user_management",
        "backup_recovery",
        "disaster_recovery",
        "patch_management",
        "vulnerability_management",
        "compliance",
        "auditing",
      ],
    },
    template_data: {
      icon: "server",
      color: "gray",
      tags: ["sysadmin", "infrastructure", "support"],
      difficulty: "intermediate",
    },
  },

  // Design Roles
  {
    id: "ui-ux-designer",
    name: "UI/UX Designer",
    description:
      "Designs user interfaces and user experiences for digital products. Creates intuitive, accessible, and visually appealing designs that enhance user satisfaction and drive business goals.",
    experience: "2+ years",
    category: "Design",
    core_competencies: {
      design_tools: [
        "figma",
        "sketch",
        "adobe_xd",
        "invision",
        "principle",
        "framer",
        "protopie",
        "zeplin",
      ],
      user_research: [
        "user_interviews",
        "usability_testing",
        "surveys",
        "personas",
        "user_journeys",
        "card_sorting",
        "tree_testing",
        "analytics",
      ],
      design_systems: [
        "design_tokens",
        "component_libraries",
        "style_guides",
        "brand_guidelines",
        "accessibility",
        "responsive_design",
        "mobile_first",
        "atomic_design",
      ],
      prototyping: [
        "wireframing",
        "mockups",
        "interactive_prototypes",
        "user_flows",
        "information_architecture",
        "navigation_design",
        "micro_interactions",
        "animation",
      ],
      collaboration: [
        "stakeholder_management",
        "developer_handoff",
        "design_reviews",
        "feedback_incorporation",
        "cross_functional_teams",
        "agile_methodology",
        "design_sprints",
        "workshops",
      ],
      technical_skills: [
        "html",
        "css",
        "javascript",
        "react",
        "vue",
        "responsive_design",
        "performance",
        "seo",
      ],
    },
    template_data: {
      icon: "palette",
      color: "pink",
      tags: ["ui", "ux", "design"],
      difficulty: "intermediate",
    },
  },
  {
    id: "graphic-designer",
    name: "Graphic Designer",
    description:
      "Creates visual designs and graphics for various platforms including print, web, and digital media. Develops brand identities, marketing materials, and visual communications that effectively convey messages and engage audiences.",
    experience: "2+ years",
    category: "Design",
    core_competencies: {
      design_software: [
        "adobe_photoshop",
        "adobe_illustrator",
        "adobe_indesign",
        "adobe_after_effects",
        "sketch",
        "figma",
        "canva",
        "affinity_designer",
      ],
      design_principles: [
        "typography",
        "color_theory",
        "composition",
        "balance",
        "contrast",
        "hierarchy",
        "spacing",
        "alignment",
      ],
      branding: [
        "logo_design",
        "brand_identity",
        "style_guides",
        "brand_guidelines",
        "visual_identity",
        "brand_strategy",
        "market_research",
        "competitive_analysis",
      ],
      print_design: [
        "brochures",
        "flyers",
        "posters",
        "business_cards",
        "packaging",
        "magazines",
        "books",
        "annual_reports",
      ],
      digital_design: [
        "web_design",
        "social_media",
        "email_templates",
        "banners",
        "infographics",
        "presentations",
        "mobile_apps",
        "icons",
      ],
      project_management: [
        "client_communication",
        "project_timelines",
        "file_organization",
        "version_control",
        "feedback_incorporation",
        "quality_assurance",
        "delivery_formats",
        "asset_management",
      ],
    },
    template_data: {
      icon: "image",
      color: "blue",
      tags: ["graphic", "visual", "branding"],
      difficulty: "intermediate",
    },
  },

  // Product Roles
  {
    id: "product-manager",
    name: "Product Manager",
    description:
      "Manages product strategy and roadmap to deliver value to customers and achieve business objectives. Coordinates with cross-functional teams to define requirements, prioritize features, and ensure successful product delivery.",
    experience: "3+ years",
    category: "Product",
    core_competencies: {
      product_strategy: [
        "market_research",
        "competitive_analysis",
        "user_research",
        "product_vision",
        "roadmap_planning",
        "feature_prioritization",
        "go_to_market",
        "pricing_strategy",
      ],
      stakeholder_management: [
        "executive_communication",
        "cross_functional_collaboration",
        "customer_interviews",
        "sales_alignment",
        "marketing_coordination",
        "engineering_partnership",
        "design_collaboration",
        "support_team_work",
      ],
      agile_methodology: [
        "scrum",
        "kanban",
        "sprint_planning",
        "user_stories",
        "acceptance_criteria",
        "backlog_management",
        "retrospectives",
        "daily_standups",
      ],
      analytics: [
        "product_analytics",
        "user_behavior",
        "conversion_tracking",
        "a_b_testing",
        "cohort_analysis",
        "funnel_analysis",
        "kpi_definition",
        "roi_measurement",
      ],
      tools: [
        "jira",
        "confluence",
        "notion",
        "figma",
        "mixpanel",
        "amplitude",
        "google_analytics",
        "slack",
      ],
      communication: [
        "presentation_skills",
        "technical_writing",
        "requirements_documentation",
        "user_documentation",
        "training_materials",
        "change_management",
        "conflict_resolution",
        "negotiation",
      ],
    },
    template_data: {
      icon: "target",
      color: "orange",
      tags: ["product", "strategy", "management"],
      difficulty: "advanced",
    },
  },
  {
    id: "project-manager",
    name: "Project Manager",
    description:
      "Manages project timelines and team coordination to ensure successful project delivery. Plans, executes, and monitors projects while managing resources, risks, and stakeholder expectations.",
    experience: "3+ years",
    category: "Product",
    core_competencies: {
      project_methodologies: [
        "agile",
        "scrum",
        "kanban",
        "waterfall",
        "prince2",
        "pmp",
        "lean",
        "six_sigma",
      ],
      planning_tools: [
        "microsoft_project",
        "jira",
        "asana",
        "trello",
        "monday",
        "smartsheet",
        "notion",
        "confluence",
      ],
      risk_management: [
        "risk_identification",
        "risk_assessment",
        "risk_mitigation",
        "contingency_planning",
        "issue_tracking",
        "change_management",
        "quality_assurance",
        "compliance",
      ],
      team_management: [
        "resource_allocation",
        "team_coordination",
        "performance_management",
        "conflict_resolution",
        "motivation",
        "communication",
        "leadership",
        "mentoring",
      ],
      stakeholder_management: [
        "client_communication",
        "status_reporting",
        "expectation_management",
        "presentation_skills",
        "negotiation",
        "vendor_management",
        "executive_updates",
        "feedback_collection",
      ],
      budgeting: [
        "cost_estimation",
        "budget_tracking",
        "resource_planning",
        "financial_reporting",
        "roi_analysis",
        "cost_optimization",
        "procurement",
        "contract_management",
      ],
    },
    template_data: {
      icon: "calendar",
      color: "blue",
      tags: ["project", "management", "coordination"],
      difficulty: "intermediate",
    },
  },

  // Marketing Roles
  {
    id: "marketing-specialist",
    name: "Marketing Specialist",
    description:
      "Handles marketing strategies and campaigns to promote products and services. Develops and executes marketing initiatives across various channels to drive brand awareness, lead generation, and customer acquisition.",
    experience: "2+ years",
    category: "Marketing",
    core_competencies: {
      digital_marketing: [
        "seo",
        "sem",
        "ppc",
        "social_media_marketing",
        "email_marketing",
        "content_marketing",
        "influencer_marketing",
        "affiliate_marketing",
      ],
      analytics: [
        "google_analytics",
        "facebook_analytics",
        "adobe_analytics",
        "mixpanel",
        "amplitude",
        "conversion_tracking",
        "attribution_modeling",
        "roi_measurement",
      ],
      content_creation: [
        "blog_writing",
        "social_media_content",
        "email_campaigns",
        "landing_pages",
        "video_content",
        "infographics",
        "case_studies",
        "whitepapers",
      ],
      tools: [
        "hubspot",
        "marketo",
        "mailchimp",
        "hootsuite",
        "buffer",
        "canva",
        "adobe_creative_suite",
        "google_ads",
      ],
      strategy: [
        "market_research",
        "competitive_analysis",
        "customer_segmentation",
        "persona_development",
        "campaign_planning",
        "budget_allocation",
        "kpi_definition",
        "performance_optimization",
      ],
      communication: [
        "brand_messaging",
        "copywriting",
        "presentation_skills",
        "stakeholder_communication",
        "cross_functional_collaboration",
        "client_management",
        "vendor_management",
        "event_management",
      ],
    },
    template_data: {
      icon: "megaphone",
      color: "green",
      tags: ["marketing", "digital", "campaigns"],
      difficulty: "intermediate",
    },
  },
  {
    id: "content-writer",
    name: "Content Writer",
    description:
      "Creates written content for various platforms including websites, blogs, social media, and marketing materials. Develops engaging, informative, and SEO-optimized content that drives traffic and converts readers into customers.",
    experience: "2+ years",
    category: "Marketing",
    core_competencies: {
      writing_skills: [
        "copywriting",
        "blog_writing",
        "technical_writing",
        "creative_writing",
        "seo_writing",
        "email_writing",
        "social_media_writing",
        "press_releases",
      ],
      content_types: [
        "articles",
        "blog_posts",
        "case_studies",
        "whitepapers",
        "ebooks",
        "landing_pages",
        "product_descriptions",
        "email_campaigns",
      ],
      seo: [
        "keyword_research",
        "on_page_seo",
        "content_optimization",
        "meta_descriptions",
        "title_tags",
        "internal_linking",
        "content_structure",
        "search_analytics",
      ],
      research: [
        "market_research",
        "competitor_analysis",
        "trend_analysis",
        "source_verification",
        "fact_checking",
        "interview_skills",
        "data_interpretation",
        "statistical_analysis",
      ],
      tools: [
        "grammarly",
        "hemingway",
        "google_docs",
        "notion",
        "trello",
        "canva",
        "adobe_creative_suite",
        "wordpress",
      ],
      collaboration: [
        "editorial_calendars",
        "content_strategy",
        "stakeholder_communication",
        "feedback_incorporation",
        "brand_voice",
        "style_guides",
        "content_approval",
        "publishing_workflows",
      ],
    },
    template_data: {
      icon: "pen-tool",
      color: "purple",
      tags: ["content", "writing", "seo"],
      difficulty: "intermediate",
    },
  },

  // Sales Roles
  {
    id: "sales-representative",
    name: "Sales Representative",
    description:
      "Manages customer relationships and sales processes to drive revenue growth. Identifies prospects, nurtures leads, and closes deals while maintaining strong customer relationships and achieving sales targets.",
    experience: "2+ years",
    category: "Sales",
    core_competencies: {
      sales_process: [
        "prospecting",
        "lead_qualification",
        "needs_assessment",
        "presentation_skills",
        "objection_handling",
        "negotiation",
        "closing_techniques",
        "follow_up",
      ],
      crm_tools: [
        "salesforce",
        "hubspot",
        "pipedrive",
        "zoho_crm",
        "monday",
        "notion",
        "airtable",
        "excel",
      ],
      communication: [
        "cold_calling",
        "email_outreach",
        "social_selling",
        "presentation_skills",
        "active_listening",
        "relationship_building",
        "customer_service",
        "conflict_resolution",
      ],
      product_knowledge: [
        "product_demos",
        "feature_explanations",
        "competitive_analysis",
        "pricing_strategy",
        "value_proposition",
        "use_cases",
        "integration_options",
        "technical_specifications",
      ],
      analytics: [
        "sales_forecasting",
        "pipeline_management",
        "conversion_tracking",
        "activity_reporting",
        "kpi_measurement",
        "territory_analysis",
        "market_research",
        "customer_insights",
      ],
      industry_knowledge: [
        "market_trends",
        "customer_pain_points",
        "competitive_landscape",
        "regulatory_requirements",
        "industry_standards",
        "best_practices",
        "case_studies",
        "success_stories",
      ],
    },
    template_data: {
      icon: "trending-up",
      color: "green",
      tags: ["sales", "revenue", "relationships"],
      difficulty: "intermediate",
    },
  },
];

export const roleCategories = [
  "Engineering",
  "Product",
  "Design",
  "Business",
  "Marketing",
  "Sales",
  "Operations",
  "General",
];

export const difficultyLevels = [
  { value: "beginner", label: "Beginner", color: "text-green-500" },
  { value: "intermediate", label: "Intermediate", color: "text-yellow-500" },
  { value: "advanced", label: "Advanced", color: "text-red-500" },
];
